### ISSUE TITLE
EndToEndId is Max35Text not 30

### ISSUE THREAD

**Issue by tjamin** [perrich/sepawriter#10]
Hello Florian,

you restrict max length of the EndToEndId to 30:

https://github.com/perrich/sepawriter/blob/master/SepaWriter/SepaTransferTransaction.cs#L45

But the XSD restricts the length to 35 not 30.

**Comment by perrich** [comment]
Thank you. You've right it should have 35 as length restriction.
In France, it seems that the length is not really managed if it's greater than 30.

I will fix it.

**Comment by perrich** [comment]
It's done.
