### ISSUE TITLE
CreateBic function "Othr" element location

### ISSUE THREAD

**Issue by Floris-van-Haaster** [perrich/sepawriter#14]
Hi,

The output file did not validate against the "pain.001.001.03.xsd"  because the **CreateBic** function contains the following:

**element.NewElement("FinInstnId")_.NewElement("BIC")_.NewElement("Othr").NewElement("Id", "NOTPROVIDED");**

I changed it to:

**element.NewElement("FinInstnId").NewElement("Othr").NewElement("Id", "NOTPROVIDED");**

Now it's working and the output file is validated correctly against: [http://www.mobilefish.com/download/sepa_xml/pain.001.001.03.xsd](http://www.mobilefish.com/download/sepa_xml/pain.001.001.03.xsd)

Best regards

Floris van Haaster

**Comment by perrich** [comment]
Hi,

Thank you. 
You're right and it's now fixed!
