### ISSUE TITLE
Creditor Address Line duplicating only on first transaction

### ISSUE THREAD

**Issue by Fyrearm** [perrich/sepawriter#21]
The AddPostalAddressElements adds pstlAdr to the first transactions Cdtr element.

I'm running the SepaInternationalCreditTransferTest test and the only thing I have done is add creditor address to the two transactions as so:

> var trans = new SepaCreditTransferTransaction
{
    Id = "Virement 458A",
    Creditor = new SepaIbanData
    {
        Bic = "PNPBUS33",
        Iban = "US29NWBK60161331926819",
        Name = "USA Factory",
        Address = new SepaPostalAddress()
        {
            AdrLine = new List<string>() { "add1", "add2" }
        }
},
    Amount = amount,
    Currency = "USD",
    EndToEndId = "SOC/1478/CC/TI001/01",
    RemittanceInformation = "En reglement des factures numeros : 123456789 987456321 258741369",
    SepaInstructionForCreditor = new SepaInstructionForCreditor() { Code = SepaInstructionForCreditor.SepaInstructionForCreditorCode.PHOB },
    Purpose = "SCVE",
    RegulatoryReportingCode = "150"
};

The attached xml is what is produced.
[APMarch1120200220.txt](https://github.com/perrich/sepawriter/files/4324468/APMarch1120200220.txt)

**Comment by perrich** [comment]
Thanks.

I've commited a fix and updated the unit test.
