### ISSUE TITLE
Wrong xmlns for pain.008.001.02

### ISSUE THREAD

**Issue by AndreK5** [perrich/sepawriter#26]
Hi.

Our financial department told me that the tag 
	<Document xmlns="urn:iso:std:iso:20022:tech:xsd:scthr:pain.008.001.02"> is wrong and after a little google research it seems that they are right and it has to be 
	<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02">

They told me that our (german) bank will not accept it that way. 

Best regards
André

**Comment by AndreK5** [comment]
uh - something got lost - here with the missing tags:

Our financial department told me that the tag
  Document xmlns="urn:iso:std:iso:20022:tech:xsd:scthr:pain.008.001.02"
should be 
  Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02"




 is wrong and after a little google research it seems that they are right and it has to be
> 
> They told me that our (german) bank will not accept it that way.
> 
> Best regards André

**Comment by perrich** [comment]
Hi, 

Please explain how to produce something with the wrong data ?

Unit test checks that without issue and the code does not contains something like this.

**Comment by AndreK5** [comment]
Hi.
I guess the definition is taken from this XSD:
https://github.com/perrich/sepawriter/blob/master/SepaWriter/Xsd/pain.008.001.02.xsd
![image](https://user-images.githubusercontent.com/93922885/141423585-5336df5d-fc63-4357-94b0-537e332fffda.png)

**Comment by AndreK5** [comment]
Hi.
for a quick test:

string FILENAME = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location) + "/sepa_debit_test_result.xml";

            SepaIbanData creditor = new SepaIbanData
            {
                Bic = "NOTPROVIDED",
                Iban = "FR7030002005500000157845Z02",
                Name = "DRK Irgendwo"
            };

            SepaDebitTransfer transfert = new SepaDebitTransfer
            {
                CreationDate = DateTime.Today,
                RequestedExecutionDate = DateTime.Today,
                MessageIdentification = "transferID",           //eindeutige ID der Dateierstellung
                PaymentInfoId = "paymentInfo",                  //Referenz zur eindeutigen Identifizierung eines Sammlers im Kontoauszug
                InitiatingPartyName = creditor.Name,
                Creditor = creditor,
                InitiatingPartyId = "ID vom DRK Irgendwo"       //Gläubiger-Identifikations-Nr.?
            };

            SepaDebitTransferTransaction debTransaction;

            debTransaction = new SepaDebitTransferTransaction
            {
                Id = "1",                
                Debtor = new SepaIbanData
                {
                    Bic = "NOTPROVIDED",                        //IBAN only-Verfahren
                    Iban = "DE89370400440532013000",
                    Name = "Theo Tischgast"
                },
                MandateIdentification = "1111",                 //SEPA-Mandatsreferenz
                DateOfSignature = new DateTime(2012, 12, 7),
                Amount = 12,
                RemittanceInformation = "Rechnungsnr. 111",
                EndToEndId = "1"
            };
            transfert.AddDebitTransfer(debTransaction);

            debTransaction = new SepaDebitTransferTransaction
            {
                Id = "2",                
                Debtor = new SepaIbanData
                {
                    Bic = "NOTPROVIDED",                        //IBAN only-Verfahren
                    Iban = "FR1420041010050500013M02606",
                    Name = "Maria Tischgast"
                },
                MandateIdentification = "2222",                 //SEPA-Mandatsreferenz
                DateOfSignature = new DateTime(2018, 12, 7),
                Amount = 22,
                RemittanceInformation = "Rechnungsnr. 112",
                EndToEndId = "2"
            };
            transfert.AddDebitTransfer(debTransaction);

            string result = transfert.AsXmlString();
            transfert.Save(FILENAME);


This creates this XML (with the additional "scthr":
![image](https://user-images.githubusercontent.com/93922885/141430597-30cb3bc7-8f83-4a85-9bfe-282b26d88fbf.png)

**Comment by perrich** [comment]
Thanks, but your code does not produce the issue.
Please debug your code but it is not related with the library.

![image](https://user-images.githubusercontent.com/3651733/141644735-47983f6a-d8d4-4809-a2ef-c8bab545d561.png)

**Comment by AndreK5** [comment]
Thanks for your reply. 

My result looks totally different ("xsi=..." is missing; additional scthr):

![image](https://user-images.githubusercontent.com/93922885/141738643-85c34cd9-dd7d-4a90-b243-fe0d2bec6dbc.png)

Where does the document definition come from?

**Comment by AndreK5** [comment]
Hi.

FYI: if I use a local generated Perrich.SepaWriter.dll then the result is ok. If I use the NUGet-Package I get this additional "scthr".

**Comment by perrich** [comment]
Hi,

Thanks, I will update the Nuget Package (maybe an issue in a previous release).

**Comment by AndreK5** [comment]
Hi. 

Do you know when you will be able to update the package?

**Comment by AndreK5** [comment]
> Hi,
> 
> Thanks, I will update the Nuget Package (maybe an issue in a previous release).

Hi,

it would be great to get an updated package...
