### ISSUE TITLE
Bic can be empty/null

### ISSUE THREAD

**Issue by DarthVader85PA** [perrich/sepawriter#28]
First of all: Thanks for that great work.

Creating a new instance of `SepaIbanData` throw a `SepaRuleException` that says a Bic must have 8 or 11 letters. But Bic can be empty. 
At the moment my workaround is: I set a Bic with 8 letters and set `BicUnknown = true`. Sepa-Xml-File are correct!!

Best regards from Germany.

**Comment by perrich** [comment]
Hi,
You've right. The Bic setter throws an exception if the provided Bic is null and has not 8 or 11 characters.
Have you tried to do not set SepaIbanData.Bic ?

`var data = new SepaIbanData
            {
                UnknownBic = true,
                Iban = "xxxxxxxxxxxxxxxx",
                Name = "yyyyyyyyyyyyy"
            };`

Regards

**Comment by DarthVader85PA** [comment]
Hi, 
thanks for you fast answer. No! You have right. I should have test it. I wrote a Wrapper for my application so sometimes I have a Bic, sometimes not.

- I added it now! 👍 
- Tested 👍 
- Can closed

```
''' <summary>
''' Gibt die Informationen aus <see cref="SepaData"/> für den Sepa-Writer als <see cref="SepaIbanData"/> zurück.
''' </summary>
''' <returns><see cref="SepaIbanData"/></returns>
Friend Function GetSepaIbanData() As SepaIbanData
    If String.IsNullOrWhiteSpace(Me.BIC) = True Then
        'Wenn die BIC fehlt, dann mit UnknownBic "NOTPROVIDED" setzen.
        Return New SepaIbanData() With {
            .Iban = Me.IBAN,
            .Name = Me.Name,
            .UnknownBic = True
        }
    Else
        'BIC vorhanden
        Return New SepaIbanData() With {
            .Bic = Me.BIC,
            .Iban = Me.IBAN,
            .Name = Me.Name,
            .UnknownBic = String.IsNullOrWhiteSpace(Me.BIC)
        }
    End If
End Function
```
