### ISSUE TITLE
CI on wrong place

### ISSUE THREAD

**Issue by Ha-Bill** [perrich/sepawriter#30]
Hello,

I used your tool to create SEPA collective direct debits in Germany, so far everything has worked.
Unfortunately, my bank's Sepa test returns an error, the creditor ID is in the wrong place!
See attached PDF.
Did I do something wrong, or is that just a problem with German banks?
[sepa-snip.pdf](https://github.com/perrich/sepawriter/files/11597102/sepa-snip.pdf)

**Comment by perrich** [comment]
According to pain.008.001.02.xsd, OrgId and PrvtId should be authorized in parent tag
But it seems that it is not always done :(.

For instance, two sample which only accept OrgId :
https://businessbanking.bankofireland.com/app/uploads/2016/07/SEPA-Direct-Debit-PAIN.008.001.02-XML-File-Structure-PDF.pdf
https://www.credit-suisse.com/media/assets/microsite/docs/zv-migration/pain-008-001-02-six.pdf
These doc accepts both :
https://www.nordea.com/en/doc/mig-pain-008-001-02-direct-debits-sepa.pdf

You can check if it works after replacing OrgId by PrvtId in SepaWriter\SepaDebitTransfer.cs

**Comment by Ha-Bill** [comment]
Thanks for the tip, it works now!
