### ISSUE TITLE
utilisation and licence

### ISSUE THREAD

**Issue by julienGrd** [perrich/sepawriter#9]
Hi Florian, I'm a french developer like you and I would like to know if I can use your project for my client (I'm freelance), in terms of licence but also how can I use them (there is no nuget package, is voluntary ?).

Thanks for your reply,

Julien

PS : I don't find any other places to contact you !

**Comment by perrich** [comment]
Hi, thank you for your query.
 
You can do near than everything with the Apache License 2. Feel free to distribute and add it in a commercial product.
I've not created a nuget package but there is no real reason (lack of time maybe). As the current requirement of the API is only with log4net, you can easily remove it or change the version (it was the case in my company). You only need to add the SepaWriter project in your code and it should work!

**Comment by julienGrd** [comment]
OK thank you ! I build the project locally and reference generated dll and it works perfectly.

good luck

Julien
